- name: install docker
  hosts: localhost
  vars:
    user: "{{ lookup('env', 'USER') }}" # default to current user

  tasks:
  - name: Install docker
    apt:
      name: docker.io
    become: true

  - name: "Add user: '{{ user }}' to docker group"
    user:
      name: '{{ user }}'
      groups: docker
      append: yes
    become: True