- name: install espanso
  hosts: localhost
  vars:
    user: "{{ lookup('env', 'USER') }}" # default to current user
    base_path: '~{{ user }}/sytup/base'
    personal_dir: '~{{ user }}/sytup/personal'
    # Directory for links to personal config files
    linked_dir: "{{ (base_path, 'config/espanso/user/linked/') | path_join }}"
  tasks:

  - name: install xclip (required by espanso, but not installed automatically)
    apt:
      name: xclip
    become: true
    
  - name: install espanso
    snap:
      name: espanso
      classic: true
    become: true

  - name: create symlink to config dir
    file:
      src: '{{ base_path }}/config/espanso'
      dest: "~{{ user }}/.config/espanso"
      state: link
    become: true
    become_user: "{{ user }}"

  - name: find personal espanso configs
    find:
      paths: '{{ personal_dir }}/config/espanso/'
    register: configs
    become: true
    become_user: "{{ user }}"
      
  - name: create linked dir
    file:
      path: "{{ linked_dir }}"
      state: directory
    become: true
    become_user: "{{ user }}"

  - name: create symlink to personal configs
    file:
      dest: '{{ ( linked_dir, (item.path | basename) ) | path_join }}'
      src: '{{ item.path }}'
      state: link
    loop: '{{ configs.files }}' # Loop over files from previous task
    become: true
    become_user: "{{ user }}"