---
- name: install git
  hosts: localhost 
  vars:
    user: "{{ lookup('env', 'USER') }}" # default to current user

  tasks:
  - name: install git
    apt:
      name: git
    become: true

  - name: "set git user.email {{ email }}"
    git_config:
      name: user.email
      scope: global
      value: "{{ email }}"
    when: email is defined
    become_user: "{{ user }}"
    become: true
      
  - name: "set git user.name to {{ fullname }}"
    git_config:
      name: user.name
      scope: global
      value: "{{ fullname }}"
    when: fullname is defined
    become_user: "{{ user }}"
    become: true