---
- name: install git
  hosts: localhost 
 
  tasks:

  - name: install git
    apt:
      name: git
    become: true

  - name: set identity email
    git_config:
      name: user.email
      scope: global
      value: "{{ email }}"
    when: email is defined
      
  - name: set identity user name
    git_config:
      name: user.name
      scope: global
      value: "{{ name }}"
    when: name is defined