- name: Setup i3-wm
  hosts: localhost
  vars:
    user: "{{ lookup('env', 'USER') }}" # default to current user
    base_path: '~{{ user }}/sytup/base'
    config_dir: "{{ ( base_path, 'config/' ) | path_join }}"
    src_dir: "{{ ( config_dir, 'i3/' ) | path_join }}"
    dest_dir: "~{{ user }}/.config/i3"
  tasks:
  - name: Install i3wm (apt)
    apt:
      name: i3
    become: true

  - name: "create config symlink {{ dest_dir }} -> {{ src_dir }}"
    file:
      src: "{{ src_dir }}"
      dest: "{{ dest_dir }}"
      state: link
    become: true
    become_user: "{{ user }}"

  - name: "create i3status config symlink"
    file:
      src: "{{ ( config_dir, 'i3status/' ) | path_join }}"
      dest: "~{{ user }}/.config/i3status"
      state: link
    become: true
    become_user: "{{ user }}"