---
- name: install vscode
  hosts: localhost
  vars:
    user: "{{ lookup('env', 'USER') }}" # defaults to current user
    extensions:
      - hbenl.vscode-test-explorer
      - littlefoxteam.vscode-python-test-adapter
      - ms-python.python
      - ms-python.vscode-pylance
      - eamodio.gitlens
      - ms-azuretools.vscode-docker
      - ms-vscode-remote.remote-containers

  tasks:
  - name: install vscode
    snap:
      name: code
      classic: true
    become: true

  - name: install extensions
    ansible.builtin.command: 
      cmd: "code --install-extension {{ item }}"
    loop: "{{ extensions }}"
    become: true
    become_user: "{{ user }}"