- name: install zsh
  hosts: localhost
  vars_files:
    - vars.yaml
    - "{{ personal_vars }}"
  
  tasks:

  - name: Install zsh
    apt:
      name: zsh
    become: true

  - name: change user shell to zsh 
    become: yes
    user:
      name: "{{ user }}"
      shell: /bin/zsh


  - name: Install galaxy role 
    command: "ansible-galaxy install gantsign.antigen"

- hosts: localhost
  vars_files:
    - vars.yaml
    - "{{ personal_vars }}"
  
  roles:
    - role: gantsign.antigen
      users:
        - username: "{{ user }}"
          antigen_libraries:
            - name: oh-my-zsh
          antigen_theme:
            name: agnoster # This role has no default theme (unlike the `gantsign.oh-my-zsh` role)
          antigen_bundles:
            - name: git # This role has no default bundles/plugins (unlike the `gantsign.oh-my-zsh` role)
            - name: zsh-syntax-highlighting
              url: zsh-users/zsh-syntax-highlighting
            - name: pip
            - name: k # ls with git annotation: https://github.com/supercrabtree/k
              url: supercrabtree/k
            - name: enhancd # improved cd command: https://github.com/b4b4r07/enhancd
              url: b4b4r07/enhancd
            - name: zsh-autosuggestions # command suggestions
              url:  zsh-users/zsh-autosuggestions 
            - name: zsh-completions
              url:  zsh-users/zsh-completions 