name: coding
parent: default
matches:

  # Ansible Playbook
  - trigger: ";ap" 
    replace: "ansible-playbook"

  # Docker Compose
  - trigger: ";dc"
    replace: "docker-compose"

  # Git Clone from GitHub
  - trigger: ";gc"
    replace: "git clone git@github.com:luftkode/$|$.git"