- name: install espanso
  hosts: localhost
  vars_files:
    - vars.yaml

  tasks:

  - name: install xclip (required by espanso, but not installed automatically)
    apt:
      name: xclip
    become: true
    
  - name: install espanso
    snap:
      name: espanso
      classic: true
    become: true

  - name: create symlink to config dir
    file:
      src: '{{ base_path }}/config/espanso'
      dest: "{{ lookup('env', 'HOME') }}/.config/espanso"
      state: link
    become: "{{ user }}"

  - name: find personal espanso configs
    find:
      paths: '{{ base_path }}/personal/espanso/'
    register: configs
    
  - name: create symlink to personal configs
    file:
      dest: '{{ base_path }}/config/espanso/user/linked/{{ item.path | basename }}'
      src: '{{ item.path }}'
      state: link
    loop: '{{ configs.files }}' # Loop over files from previous task
    become: gp