---
- name: Setup alacritty
  hosts: localhost 
  vars:
    user: "{{ lookup('env', 'USER') }}" # default to current user
    base_path: '/sytup/base'
    config_dir: "{{ ( base_path, 'config/' ) | path_join }}"
    src_dir: "{{ ( config_dir, 'alacritty/' ) | path_join }}"
    dest_dir: "~{{ user }}/.config/alacritty"

  tasks:
  - name: Setup alacritty repo
    apt_repository:
      repo: ppa:aslatter/ppa
    become: true

  - name: Install alacritty
    apt:
      name: alacritty
    become: true

  - name: "create config symlink {{ dest_dir }} -> {{ src_dir }}"
    file:
      src: "{{ src_dir }}"
      dest: "{{ dest_dir }}"
      state: link
    become: true
    become_user: "{{ user }}"