- name: Install fontconfig
  hosts: localhost

  roles:
    - role: sicruse.powerline-fonts
      tags: packages

  tasks:
    - name: remove tmp dir for user install
      file:
        path: /tmp/powerline-fonts
        state: absent

- name: Install powerline fonts
  hosts: localhost
  vars:
    user: "{{ lookup('env', 'USER') }}" # default to current user

  roles:
    - role: sicruse.powerline-fonts
      become: true
      become_user: "{{ user }}"
      powerline_users:              # this role can configure for one or more users
        - user: "{{ user }}"         # username. Defaults to current user

      powerline_fonts:              # the fonts you want to install. Defaults shown here.
        - RobotoMono          # the name of these fonts must match the name of the
        - SourceCodePro       # font directory
        - DejaVuSansMono
        - UbuntuMono
  
  tasks:
    - name: remove tmp dir
      become: true
      become_user: "{{ user }}"
      file:
        path: /tmp/powerline-fonts
        state: absent