- name: install zsh
  hosts: localhost
  vars_files:
    - ../vars.yaml
    - "{{ personal_vars }}"
  
  tasks:

  - name: Install zsh
    apt:
      name: zsh
    become: true

  - name: change user shell to zsh 
    become: yes
    user:
      name: "{{ user }}"
      shell: /bin/zsh